# Generated by Django 2.2 on 2019-06-03 12:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateField(default=datetime.date(2019, 6, 3))),
                ('ends_at', models.DateField(default=datetime.date(2019, 7, 3))),
                ('goal', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='MandatoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('-', 'expense'), ('+', 'income')], max_length=1)),
                ('amount', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999999.99)])),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Period')),
            ],
        ),
    ]
