# Generated by Django 2.2 on 2019-06-04 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20190603_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandatorytransaction',
            name='owner',
        ),
        migrations.AlterField(
            model_name='period',
            name='ends_at',
            field=models.DateField(default=datetime.date(2019, 7, 4)),
        ),
    ]
