# Generated by Django 2.2 on 2019-06-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20190604_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatorytransaction',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatorytransaction_set', to='planning.Period'),
        ),
    ]
