# Generated by Django 2.2 on 2019-05-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'holder': 'self.owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Account'),
        ),
    ]
