# Generated by Django 2.2 on 2019-05-16 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20190516_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
