# Generated by Django 2.2 on 2019-06-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20190620_1025'),
        ('transactions', '0012_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='planned_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.MandatoryTransaction'),
        ),
    ]
